rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  no-vendor-prefixes: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  no-css-comments: 0
  indentation:
    - 2
    -
      size: 2
  property-sort-order: 0
  no-transition-all: 0
  leading-zero: 0
  class-name-format: 0
  pseudo-element: 0
  nesting-depth:
    - 1
    -
      max-depth: 3